# Generated by Django 4.0.1 on 2022-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bizning_faxrimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(null=True, upload_to='rasmlar/%Y/%m/%d')),
                ('ism_sharif', models.CharField(max_length=100)),
                ('malumot', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'verbose_name': 'Bizning faxrimiz',
                'verbose_name_plural': 'Bizning faxrimiz',
            },
        ),
        migrations.CreateModel(
            name='Kurs_narxlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_nomi', models.CharField(max_length=100)),
                ('kurs_narxi', models.IntegerField()),
                ('kurs_haqida', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Kurs narxi',
                'verbose_name_plural': 'Kurs narxlari',
            },
        ),
        migrations.CreateModel(
            name='Menyu_Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_nomi', models.CharField(max_length=100)),
                ('fan_haqida', models.CharField(max_length=130)),
            ],
            options={
                'verbose_name': 'Fan Menyusi',
                'verbose_name_plural': 'Fanlar Menyusi',
            },
        ),
        migrations.CreateModel(
            name='Oqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(null=True, upload_to='rasmlar/%Y/%m/%d')),
                ('ism_sharif', models.CharField(max_length=100)),
                ('vazifasi', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijtimoiy_tarmoq', models.IntegerField()),
                ('oquvchilar_soni', models.IntegerField()),
                ('kontentlar_soni', models.IntegerField()),
                ('ustozlar_soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(null=True, upload_to='rasmlar/%Y/%m/%d')),
                ('sarlavha', models.CharField(max_length=100)),
                ('vaqt', models.DateField(auto_now_add=True)),
                ('malumot', models.TextField()),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'yangiliklar',
            },
        ),
    ]
