# Generated by Django 4.0.1 on 2022-05-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_menyu_fanlar_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='kurishlar',
            field=models.IntegerField(default=1),
        ),
    ]
